// ── FRASES DEL DÍA ──
const QUOTES = [
  "El dolor de hoy es el cuerpo que querías mañana.",
  "No tienes que tener ganas. Tienes que hacerlo igual.",
  "Cada excusa que te crees es un día más que no avanzas.",
  "La comodidad no construyó ningún cuerpo que valga la pena.",
  "Tu cuerpo puede hacer más. Tu mente es el problema.",
  "No le pidas al mundo que sea más fácil. Pídete ser más fuerte.",
  "El único que sabe cuánto te costó eres tú.",
  "80 días. Sin negociar.",
  "Cuando quieras rendirte, recuerda por qué empezaste.",
  "El resultado no se negocia. O te mueves o te quedas.",
  "No hay atajos en agosto.",
  "Cada kilo que bajes es una guerra ganada.",
  "La disciplina es libertad. El descanso sin mérito es jaula.",
  "No sigas tus ganas. Sigue tu plan.",
  "Hoy eres la única competencia que importa.",
  "No hay nadie que lo haga por ti. Nunca lo habrá.",
  "La versión que quieres ser no nace sola.",
  "El hambre de cambio tiene que ser más grande que el hambre de excusas.",
  "Rendirse es permanente. El esfuerzo es temporal.",
  "Cada repetición que odias es la que más importa.",
  "No te pido que lo disfrutes. Te pido que lo hagas.",
  "El sacrificio de hoy es el cuerpo de agosto.",
  "Nadie recuerda a los que casi lo lograron.",
  "Tu futuro yo ya sabe lo que estás haciendo hoy.",
  "La grasa no tiene opinión. Tú sí. Úsala.",
  "No es motivación. Es obligación.",
  "Un día sin registrar es un día sin datos. Los datos no mienten.",
  "El cansancio es mentira. La rendición es permanente.",
  "Haz lo que planeaste, aunque no sientas nada.",
  "No existe el 'mañana lo compenso'. Existe hoy o no existe.",
  "La consistencia aburre a los mediocres y construye a los mejores.",
  "Si fuera fácil, todos tendrían el cuerpo que quieres.",
  "No necesitas aplausos. Necesitas resultados.",
  "El espejo no miente. Las excusas sí.",
  "Cada día que entrenas eres mejor que el que no entrena. Sin excepciones.",
  "El progreso no se siente. Se mide.",
  "Hoy no es un buen día para rendirse.",
  "Levántate como si ya fueras la persona que quieres ser.",
  "La mente flaquea antes que el cuerpo. No le hagas caso.",
  "Tienes 80 días. Cada uno cuenta el doble.",
  "Proteína, entreno, sueño. No hay secreto más grande que ese.",
  "No necesitas perfección. Necesitas consistencia.",
  "El que no registra no progresa. El que no progresa se estanca.",
  "Hoy puede doler. El arrepentimiento dura más.",
  "Ningún cheat day vale más que tu meta.",
  "La báscula sube y baja. La disciplina es constante.",
  "No eres débil. Solo estás eligiendo serlo.",
  "El cuerpo sigue al hábito. Construye el hábito.",
  "Cuatro meses de tu vida por un cuerpo que dure años. Haz las cuentas.",
  "El peor entreno siempre es el que no hiciste.",
  "No es sobre cómo te sientes. Es sobre qué decides.",
  "Date el respeto que le pides al mundo.",
  "Agosto 15 llega igual, hagas lo que hagas. La pregunta es cómo llegas tú.",
  "Aquí no hay días libres de mentalidad.",
  "Tu cuerpo guarda todo: lo que comes, lo que entrenas, lo que ignoras.",
  "La diferencia entre quien llega y quien no es solo la consistencia.",
  "No necesitas sentirte listo. Necesitas empezar.",
  "Cada macro contado es una batalla ganada contra el azar.",
  "El cuerpo que quieres no te va a esperar sentado.",
  "No hay versión fácil de esto. Solo hay la versión que funciona.",
  "Cuando te cueste, recuerda: eso es exactamente cuando más importa.",
  "80 días no son para siempre. Tu cuerpo en agosto, sí.",
  "No compitas con nadie. Solo con quien fuiste ayer.",
  "Si hoy no entrenas, mañana tienes que entrenar más fuerte.",
  "El proceso no es bonito. El resultado sí.",
  "El músculo no crece pidiendo permiso. Tú tampoco.",
  "Sufre ahora. Brilla en agosto.",
  "Cada 'no quiero' que ignoras te hace más fuerte.",
  "La transformación no es un destino. Es una decisión que tomas todos los días.",
  "No hay motivación que reemplace al sistema.",
  "Cuando tu cuerpo diga no, tu mente dice siguiente repetición.",
  "No esperes a estar listo. La preparación llega sola cuando actúas.",
  "El que sigue cuando no quiere llega. El que para cuando no quiere no llega.",
  "Mide lo que importa. Ignora lo que no.",
  "No hay cuerpo de agosto sin julio. No hay julio sin junio.",
  "El sudor de hoy paga la confianza de mañana.",
  "Hazte responsable. Nadie más lo va a hacer.",
  "Si no tienes ganas hoy, hazlo sin ganas. El resultado es el mismo.",
  "El descanso tiene que ganarse.",
  "No le debes explicaciones a nadie. Solo resultados a ti mismo.",
  "Un cuerpo transformado no nace en el gimnasio. Nace en la cabeza.",
  "Hoy puedes elegir el dolor del entreno o el dolor del arrepentimiento.",
  "No hay lugar para mediocridad en 80 días.",
  "Los días fáciles no te construyeron. Los difíciles sí.",
  "La báscula es solo un número. Tus acciones son todo.",
  "Haz lo que dijiste que ibas a hacer.",
  "No necesitas inspiración. Necesitas ejecución.",
  "Tu cuerpo es el reflejo de tus decisiones. Toma mejores decisiones.",
  "No importa lo lento que vayas, siempre es más rápido que quien no se mueve.",
  "Cuando el proceso se vuelve rutina, la transformación se vuelve inevitable.",
  "No duermas como quien no tiene metas.",
  "Cada día que completas este programa eres distinto al de ayer.",
  "La comodidad es el enemigo disfrazado de descanso.",
  "No busques validación. Busca resultados.",
  "El cuerpo que construyes hoy es la armadura que usas mañana.",
  "Sin datos no hay progreso. Sin progreso no hay transformación.",
  "Hoy es el día más joven que vas a ser. Úsalo.",
  "No hay opción B. Solo existe el plan.",
  "Cada mañana que entrenas le ganas terreno a quien duerme.",
  "La transformación empieza donde termina tu zona de confort."
];
